version: '3'
services:
  selenoid:
    image: "aerokube/selenoid"
    command: -listen :4444 -conf /etc/selenoid/browsers.json -video-output-dir /opt/selenoid/video/ -timeout 3m
    network_mode: bridge
    ports:
      - "4444:4444"
    volumes:
      - ".:/etc/selenoid/" # assumed current dir contains browsers.json
      - "/var/run/docker.sock:/var/run/docker.sock" 
      - "/home/ubuntu/media:/media/upload"
      - /./../onboard/tests/media1:/home/selenium/Downloads
    command: "-enable-file-upload"
  selenoid-ui:
    image: "aerokube/selenoid-ui"
    network_mode: bridge
    links:
      - selenoid
    ports:
      - "8080:8080"
    command: ["--selenoid-uri", "http://172.17.0.1:4444"]
